In [1]:
import numpy as np
import pandas as pd
import sklearn.metrics as metrics
from sklearn.neural_network import MLPClassifier
from sklearn import svm

In [2]:
# Get the feature of the training set
def get_features(filename):
    features = pd.read_csv('./'+filename)
    print(features.head(12))
    # train = train.sample(frac=1).reset_index(drop=True)
    # print(train.head())
    return features

# Get the labels of the training set
def get_labels(filename):
    labels = pd.read_csv('./'+filename)
    print(labels.head(12))
    # train = train.sample(frac=1).reset_index(drop=True)
    # print(train.head())
    return labels

# Get the features of the testing set
def get_test_feature(filename):
    test_features = pd.read_csv('./'+filename)
    print(test_features.head(12))
    # train = train.sample(frac=1).reset_index(drop=True)
    # print(train.head())
    return test_features

train_features = get_features('train_features.csv')
labels = get_labels('train_labels.csv')
test_features = get_test_feature('test_features.csv')
print(features.shape)
print(labels.shape)
print(test_features.shape)

    pid  Time   Age  EtCO2  PTT   BUN  Lactate  Temp  Hgb  HCO3  ...  \
0     1     3  34.0    NaN  NaN  12.0      NaN  36.0  8.7  24.0  ...
1     1     4  34.0    NaN  NaN   NaN      NaN  36.0  NaN   NaN  ...
2     1     5  34.0    NaN  NaN   NaN      NaN  36.0  NaN   NaN  ...
3     1     6  34.0    NaN  NaN   NaN      NaN  37.0  NaN   NaN  ...
4     1     7  34.0    NaN  NaN   NaN      NaN   NaN  NaN   NaN  ...
5     1     8  34.0    NaN  NaN   NaN      NaN  37.0  NaN   NaN  ...
6     1     9  34.0    NaN  NaN   NaN      NaN  37.0  NaN   NaN  ...
7     1    10  34.0    NaN  NaN   NaN      NaN  37.0  NaN   NaN  ...
8     1    11  34.0    NaN  NaN  12.0      NaN   NaN  8.5  26.0  ...
9     1    12  34.0    NaN  NaN  12.0      NaN  38.0  8.5  26.0  ...
10    1    13  34.0    NaN  NaN   NaN      NaN   NaN  NaN   NaN  ...
11    1    14  34.0    NaN  NaN   NaN      NaN   NaN  NaN   NaN  ...

    Alkalinephos   SpO2  Bilirubin_direct  Chloride   Hct  Heartrate  \
0            NaN  100.0               NaN     114.0  24.6       94.0
1            NaN  100.0               NaN       NaN   NaN       99.0
2            NaN  100.0               NaN       NaN   NaN       92.0
3            NaN  100.0               NaN       NaN   NaN       88.0
4            NaN  100.0               NaN       NaN  22.4       81.0
5            NaN  100.0               NaN       NaN  22.4       82.0
6            NaN  100.0               NaN       NaN   NaN       67.0
7            NaN  100.0               NaN       NaN   NaN       62.0
8            NaN  100.0               NaN     111.0  23.8       58.0
9            NaN  100.0               NaN     111.0  23.8       66.0
10           NaN  100.0               NaN       NaN   NaN       67.0
11           NaN  100.0               NaN       NaN  22.2       69.0

    Bilirubin_total  TroponinI   ABPs    pH
0               NaN        NaN  142.0  7.33
1               NaN        NaN  125.0  7.33
2               NaN        NaN  110.0  7.37
3               NaN        NaN  104.0  7.37
4               NaN        NaN  100.0  7.41
5               NaN        NaN  106.0   NaN
6               NaN        NaN  112.0   NaN
7               NaN        NaN  121.0   NaN
8               NaN        NaN  118.0   NaN
9               NaN        NaN  110.0  7.39
10              NaN        NaN  124.0  7.39
11              NaN        NaN  102.0   NaN

[12 rows x 37 columns]
      pid  LABEL_BaseExcess  LABEL_Fibrinogen  LABEL_AST  LABEL_Alkalinephos  \
0       1               1.0               0.0        0.0                 0.0
1      10               0.0               0.0        0.0                 0.0
2     100               1.0               0.0        0.0                 0.0
3    1000               0.0               0.0        0.0                 0.0
4   10000               0.0               0.0        0.0                 0.0
5   10002               0.0               0.0        0.0                 0.0
6   10006               0.0               0.0        0.0                 0.0
7   10007               0.0               0.0        1.0                 1.0
8   10009               1.0               1.0        0.0                 0.0
9    1001               1.0               0.0        0.0                 0.0
10  10010               0.0               0.0        0.0                 0.0
11  10012               0.0               0.0        1.0                 1.0

    LABEL_Bilirubin_total  LABEL_Lactate  LABEL_TroponinI  LABEL_SaO2  \
0                     0.0            1.0              0.0         0.0
1                     0.0            0.0              0.0         0.0
2                     0.0            1.0              0.0         0.0
3                     0.0            1.0              0.0         1.0
4                     0.0            0.0              0.0         0.0
5                     0.0            0.0              0.0         0.0
6                     0.0            0.0              0.0         0.0
7                     1.0            0.0              0.0         0.0
8                     0.0            1.0              0.0         1.0
9                     0.0            1.0              0.0         0.0
10                    0.0            0.0              1.0         0.0
11                    1.0            0.0              0.0         0.0

    LABEL_Bilirubin_direct  LABEL_EtCO2  LABEL_Sepsis  LABEL_RRate  \
0                      0.0          0.0           0.0         12.1
1                      0.0          0.0           0.0         17.8
2                      0.0          0.0           0.0         16.5
3                      0.0          1.0           0.0         19.4
4                      0.0          0.0           0.0         12.6
5                      0.0          0.0           0.0         14.5
6                      0.0          0.0           0.0         17.2
7                      0.0          0.0           1.0         23.8
8                      0.0          0.0           0.0         18.9
9                      0.0          0.0           0.0         14.9
10                     0.0          0.0           0.0         20.5
11                     0.0          0.0           0.0         19.8

    LABEL_ABPm  LABEL_SpO2  LABEL_Heartrate
0         85.4       100.0             59.9
1        100.6        95.5             85.5
2         88.3        96.5            108.1
3         77.2        98.3             80.9
4         76.8        97.7             95.3
5         67.4        99.1             64.6
6         84.9        96.8             90.5
7         97.0        94.3             76.0
8         72.0        95.3             91.5
9         83.3        99.9            117.3
10        72.2        97.7             84.3
11        95.8        97.6            101.6
    pid  Time   Age  EtCO2   PTT   BUN  Lactate  Temp   Hgb  HCO3  ...  \
0     0     1  39.0    NaN   NaN   NaN      NaN   NaN   NaN   NaN  ...
1     0     2  39.0    NaN  44.2  17.0      NaN  36.0  10.2  13.0  ...
2     0     3  39.0    NaN   NaN   NaN      NaN   NaN   NaN   NaN  ...
3     0     4  39.0    NaN   NaN   NaN      NaN   NaN   NaN   NaN  ...
4     0     5  39.0    NaN   NaN   NaN      NaN   NaN   NaN   NaN  ...
5     0     6  39.0    NaN   NaN   NaN      NaN  36.0   NaN   NaN  ...
6     0     7  39.0    NaN  38.5  20.0      NaN   NaN   9.1  16.0  ...
7     0     8  39.0    NaN   NaN   NaN      NaN  36.0   NaN   NaN  ...
8     0     9  39.0    NaN   NaN   NaN      NaN  36.0   NaN   NaN  ...
9     0    10  39.0    NaN   NaN   NaN      NaN  36.0   NaN   NaN  ...
10    0    11  39.0    NaN   NaN   NaN      NaN   NaN   NaN   NaN  ...
11    0    12  39.0    NaN   NaN   NaN      NaN   NaN   NaN   NaN  ...

    Alkalinephos   SpO2  Bilirubin_direct  Chloride   Hct  Heartrate  \
0            NaN    NaN               NaN       NaN   NaN        NaN
1          119.0  100.0               NaN      98.0  31.0       82.0
2            NaN  100.0               NaN       NaN   NaN       78.0
3            NaN  100.0               NaN       NaN   NaN       80.0
4            NaN  100.0               NaN       NaN   NaN       83.0
5            NaN  100.0               NaN       NaN   NaN       88.0
6          109.0  100.0               NaN     102.0  25.9        NaN
7            NaN  100.0               NaN       NaN   NaN       90.0
8            NaN  100.0               NaN       NaN   NaN       90.0
9            NaN  100.0               NaN       NaN   NaN       85.0
10           NaN    NaN               NaN       NaN   NaN        NaN
11           NaN    NaN               NaN       NaN   NaN        NaN

    Bilirubin_total  TroponinI   ABPs    pH
0               NaN        NaN    NaN   NaN
1              21.8        NaN  119.0   NaN
2               NaN        NaN  125.0  7.34
3               NaN        NaN  136.0   NaN
4               NaN        NaN  135.0   NaN
5               NaN        NaN  144.0   NaN
6              26.4        NaN    NaN   NaN
7               NaN        NaN  129.0  7.40
8               NaN        NaN  121.0   NaN
9               NaN        NaN  120.0   NaN
10              NaN        NaN    NaN   NaN
11              NaN        NaN    NaN   NaN

[12 rows x 37 columns]

NameError: name 'features' is not defined

In [4]:
train_features = train_features.drop(columns = ['pid', 'Time'])
test_features = test_features.drop(columns = ['pid', 'Time'])

In [5]:
train_features.head(12)

,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,BaseExcess,RRate,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,34.0,NaN,NaN,12.0,NaN,36.0,8.7,24.0,-2.0,16.0,...,NaN,100.0,NaN,114.0,24.6,94.0,NaN,NaN,142.0,7.33
1,34.0,NaN,NaN,NaN,NaN,36.0,NaN,NaN,-2.0,16.0,...,NaN,100.0,NaN,NaN,NaN,99.0,NaN,NaN,125.0,7.33
2,34.0,NaN,NaN,NaN,NaN,36.0,NaN,NaN,0.0,18.0,...,NaN,100.0,NaN,NaN,NaN,92.0,NaN,NaN,110.0,7.37
3,34.0,NaN,NaN,NaN,NaN,37.0,NaN,NaN,0.0,18.0,...,NaN,100.0,NaN,NaN,NaN,88.0,NaN,NaN,104.0,7.37
4,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,...,NaN,100.0,NaN,NaN,22.4,81.0,NaN,NaN,100.0,7.41
5,34.0,NaN,NaN,NaN,NaN,37.0,NaN,NaN,NaN,16.0,...,NaN,100.0,NaN,NaN,22.4,82.0,NaN,NaN,106.0,NaN
6,34.0,NaN,NaN,NaN,NaN,37.0,NaN,NaN,NaN,18.0,...,NaN,100.0,NaN,NaN,NaN,67.0,NaN,NaN,112.0,NaN
7,34.0,NaN,NaN,NaN,NaN,37.0,NaN,NaN,NaN,18.0,...,NaN,100.0,NaN,NaN,NaN,62.0,NaN,NaN,121.0,NaN
8,34.0,NaN,NaN,12.0,NaN,NaN,8.5,26.0,NaN,12.0,...,NaN,100.0,NaN,111.0,23.8,58.0,NaN,NaN,118.0,NaN
9,34.0,NaN,NaN,12.0,NaN,38.0,8.5,26.0,0.0,18.0,...,NaN,100.0,NaN,111.0,23.8,66.0,NaN,NaN,110.0,7.39
10,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,18.0,...,NaN,100.0,NaN,NaN,NaN,67.0,NaN,NaN,124.0,7.39
11,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,...,NaN,100.0,NaN,NaN,22.2,69.0,NaN,NaN,102.0,NaN

In [8]:
# Average multiple tests on one patient in the training set
average_train_features = train_features.groupby(np.arange(len(train_features))//12).mean()
print(average_train_features.shape)

# Check now how many are still NaN
for index, row in average_train_features.iteritems():
    print(average_train_features[index].isnull().sum())
average_train_features.head(12)

(18995, 35)
0
17673
11179
5029
14123
443
5020
11158
13298
152
17281
9666
5654
5268
11223
14199
11317
5454
13940
2665
107
6669
3998
3882
6729
14251
22
18372
10644
4356
7
14284
16203
398
11001

,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,BaseExcess,RRate,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,34.0,NaN,NaN,12.0,NaN,36.750000,8.566667,25.333333,-0.666667,17.000000,...,NaN,100.000000,NaN,112.0,23.2,77.083333,NaN,NaN,114.500000,7.370
1,71.0,NaN,27.80,12.0,NaN,36.000000,14.600000,NaN,NaN,18.090909,...,68.0,98.000000,NaN,NaN,42.1,78.818182,1.3,0.01,132.909091,NaN
2,68.0,NaN,20.90,21.0,NaN,36.250000,12.500000,27.000000,NaN,14.833333,...,NaN,96.500000,NaN,101.0,36.8,109.083333,NaN,NaN,117.000000,NaN
3,79.0,31.863636,NaN,22.0,3.855,36.818182,9.200000,NaN,NaN,12.000000,...,NaN,98.818182,NaN,NaN,27.3,86.363636,NaN,NaN,141.909091,7.300
4,76.0,NaN,28.55,22.0,NaN,36.750000,10.700000,25.500000,1.500000,12.090909,...,NaN,98.545455,NaN,103.5,30.3,77.090909,NaN,NaN,123.000000,7.390
5,73.0,19.000000,31.30,18.0,3.005,37.000000,10.400000,NaN,NaN,19.625000,...,38.0,99.181818,NaN,107.0,30.3,67.090909,0.8,NaN,132.090909,7.375
6,51.0,NaN,NaN,NaN,NaN,37.500000,NaN,NaN,NaN,18.888889,...,NaN,96.666667,NaN,NaN,NaN,82.000000,NaN,NaN,117.888889,NaN
7,60.0,NaN,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,21.909091,...,NaN,94.909091,NaN,NaN,NaN,79.909091,NaN,0.08,139.363636,NaN
8,69.0,NaN,86.05,15.0,NaN,37.250000,12.200000,21.000000,NaN,22.500000,...,64.0,97.090909,NaN,104.0,34.0,97.727273,0.8,NaN,90.909091,NaN
9,36.0,NaN,31.20,10.0,1.800,37.666667,10.400000,31.000000,7.500000,13.363636,...,NaN,100.000000,NaN,105.0,29.8,106.727273,NaN,NaN,113.090909,7.515
10,85.0,NaN,NaN,119.0,NaN,36.000000,8.333333,NaN,NaN,18.636364,...,NaN,99.909091,NaN,NaN,24.2,73.818182,NaN,0.03,100.727273,NaN
11,63.0,NaN,NaN,NaN,NaN,37.000000,NaN,NaN,NaN,16.454545,...,NaN,99.000000,NaN,NaN,NaN,82.454545,NaN,NaN,101.272727,7.395

In [10]:
# Average multiple tests on one patient in the test set, also impute it using the same KNN imputer
average_test_features = test_features.groupby(np.arange(len(test_features))//12).mean()
print(average_test_features.shape)
average_test_features.head(12)

# Check now how many are still NaN
for index, row in average_test_features.iteritems():
    print(average_test_features[index].isnull().sum())
average_test_features.head(12)

(12664, 35)
0
11793
7437
3307
9312
290
3324
7382
8828
102
11572
6465
3779
3489
7400
9466
7522
3698
9233
1802
66
4391
2619
2657
4447
9501
14
12260
7021
2900
2
9534
10843
240
7254

,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,BaseExcess,RRate,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,39.0,NaN,41.35,18.5,NaN,36.000000,9.65,14.5,-6.5,11.714286,...,114.0,100.000000,NaN,100.0,28.450000,84.500000,24.1,NaN,128.625000,7.3700
1,62.0,NaN,NaN,NaN,NaN,37.250000,NaN,NaN,NaN,16.666667,...,NaN,94.200000,NaN,NaN,NaN,111.400000,NaN,NaN,111.444444,NaN
2,72.0,NaN,NaN,NaN,2.01,36.909091,NaN,NaN,NaN,16.818182,...,NaN,99.636364,NaN,NaN,NaN,91.000000,NaN,NaN,124.909091,7.4600
3,44.0,NaN,NaN,10.0,NaN,36.250000,12.70,NaN,NaN,13.857143,...,123.0,95.727273,NaN,NaN,37.500000,87.636364,0.2,NaN,94.727273,NaN
4,88.0,NaN,39.90,42.0,NaN,36.000000,8.80,25.0,NaN,19.272727,...,NaN,95.909091,NaN,108.0,29.600000,54.818182,NaN,NaN,130.100000,NaN
5,59.0,NaN,21.60,39.0,1.70,36.500000,12.80,26.0,3.5,18.583333,...,79.0,98.250000,NaN,108.5,37.200000,71.250000,NaN,NaN,154.000000,7.5450
6,45.0,NaN,NaN,7.0,NaN,36.000000,9.00,NaN,NaN,14.909091,...,NaN,99.545455,NaN,NaN,27.200000,66.181818,NaN,NaN,149.090909,NaN
7,36.0,NaN,23.60,4.5,NaN,36.666667,12.50,NaN,NaN,22.400000,...,72.0,98.600000,NaN,NaN,38.100000,106.600000,0.4,NaN,162.700000,NaN
8,65.0,42.25,NaN,23.0,NaN,38.000000,8.70,NaN,NaN,17.800000,...,NaN,94.545455,NaN,NaN,29.500000,109.636364,NaN,NaN,106.000000,7.3400
9,84.0,NaN,NaN,23.0,NaN,36.363636,9.40,23.0,-2.0,15.181818,...,NaN,96.363636,NaN,111.0,29.266667,67.727273,NaN,NaN,116.181818,7.3675
10,23.0,NaN,NaN,NaN,NaN,37.250000,NaN,NaN,NaN,22.500000,...,NaN,100.000000,NaN,NaN,NaN,111.909091,NaN,0.07,162.700000,NaN
11,51.0,NaN,31.40,17.0,NaN,38.000000,10.40,NaN,NaN,18.000000,...,162.0,100.000000,NaN,NaN,32.700000,105.000000,2.3,NaN,145.000000,NaN

In [11]:
# Use KNN to impute data
from sklearn.impute import KNNImputer

In [40]:
# Impute the training features
imputer = KNNImputer(n_neighbors=100)
imputed = imputer.fit_transform(average_train_features)
imputed_train_features = pd.DataFrame(imputed, columns=average_train_features.columns)

imputed_train_features.head(12)

,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,BaseExcess,RRate,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,34.0,34.062933,38.837167,12.000000,2.181737,36.750000,8.566667,25.333333,-0.666667,17.000000,...,70.781667,100.000000,1.091900,112.000000,23.200000,77.083333,1.624833,7.940550,114.500000,7.370000
1,71.0,35.252562,27.800000,12.000000,2.230807,36.000000,14.600000,25.401000,1.416470,18.090909,...,68.000000,98.000000,0.182000,103.890000,42.100000,78.818182,1.300000,0.010000,132.909091,7.404997
2,68.0,34.604392,20.900000,21.000000,2.272037,36.250000,12.500000,27.000000,-0.800131,14.833333,...,88.868333,96.500000,1.030233,101.000000,36.800000,109.083333,1.265000,8.949517,117.000000,7.376090
3,79.0,31.863636,37.419083,22.000000,3.855000,36.818182,9.200000,24.096292,0.112762,12.000000,...,72.195000,98.818182,0.816800,106.459048,27.300000,86.363636,1.081000,4.392300,141.909091,7.300000
4,76.0,31.116117,28.550000,22.000000,2.023025,36.750000,10.700000,25.500000,1.500000,12.090909,...,61.108333,98.545455,0.941900,103.500000,30.300000,77.090909,1.139333,4.066117,123.000000,7.390000
5,73.0,19.000000,31.300000,18.000000,3.005000,37.000000,10.400000,23.507583,-0.404592,19.625000,...,38.000000,99.181818,1.003900,107.000000,30.300000,67.090909,0.800000,5.730233,132.090909,7.375000
6,51.0,33.361052,38.671900,22.355667,2.589522,37.500000,10.697500,23.501500,0.429500,18.888889,...,87.389500,96.666667,1.989783,105.037667,30.712167,82.000000,2.273000,5.906750,117.888889,7.383335
7,60.0,34.158848,39.219167,22.435000,1.520630,38.000000,11.278833,24.720000,1.083958,21.909091,...,94.170000,94.909091,0.636700,104.066333,34.096433,79.909091,0.917000,0.080000,139.363636,7.392008
8,69.0,34.005126,86.050000,15.000000,1.844068,37.250000,12.200000,21.000000,-0.700998,22.500000,...,64.000000,97.090909,0.291400,104.000000,34.000000,97.727273,0.800000,4.233417,90.909091,7.371989
9,36.0,34.277896,31.200000,10.000000,1.800000,37.666667,10.400000,31.000000,7.500000,13.363636,...,83.590000,100.000000,0.761000,105.000000,29.800000,106.727273,0.918000,3.717450,113.090909,7.515000
10,85.0,34.219387,51.951333,119.000000,2.133950,36.000000,8.333333,20.965167,-0.122577,18.636364,...,129.923333,99.909091,1.667383,105.005333,24.200000,73.818182,2.439333,0.030000,100.727273,7.373865
11,63.0,35.058678,40.410333,23.181667,1.942883,37.000000,10.204417,24.745000,1.024978,16.454545,...,93.822500,99.000000,1.207517,104.435833,30.470117,82.454545,1.637750,12.044550,101.272727,7.395000

In [41]:
# Also impute the test features
imputed_test = imputer.transform(average_test_features)
imputed_test_features = pd.DataFrame(imputed_test, columns=average_test_features.columns)

imputed_test_features.head(12)

,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,BaseExcess,RRate,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,39.0,34.912632,41.350000,18.500000,2.307592,36.000000,9.650000,14.500000,-6.500000,11.714286,...,114.000000,100.000000,0.793400,100.000000,28.450000,84.500000,24.100000,6.892000,128.625000,7.370000
1,62.0,31.131974,44.283600,23.672667,2.408173,37.250000,11.245200,24.007708,-0.626911,16.666667,...,104.752667,94.200000,1.168000,104.863250,33.848426,111.400000,1.875233,12.812317,111.444444,7.374853
2,72.0,31.151981,34.196867,20.165000,2.010000,36.909091,9.717083,22.984833,-1.874585,16.818182,...,72.960000,99.636364,0.973100,107.543333,29.013583,91.000000,1.078833,7.200100,124.909091,7.460000
3,44.0,34.107477,40.782000,10.000000,1.839279,36.250000,12.700000,24.143381,-0.096286,13.857143,...,123.000000,95.727273,0.606800,107.902000,37.500000,87.636364,0.200000,3.899550,94.727273,7.373254
4,88.0,30.773419,39.900000,42.000000,1.668725,36.000000,8.800000,25.000000,0.108958,19.272727,...,102.485000,95.909091,0.346500,108.000000,29.600000,54.818182,0.879000,4.226417,130.100000,7.387883
5,59.0,35.041703,21.600000,39.000000,1.700000,36.500000,12.800000,26.000000,3.500000,18.583333,...,79.000000,98.250000,1.273033,108.500000,37.200000,71.250000,0.985167,6.506950,154.000000,7.545000
6,45.0,32.925361,39.649667,7.000000,1.736322,36.000000,9.000000,24.770000,0.232798,14.909091,...,82.407500,99.545455,1.054400,105.255000,27.200000,66.181818,1.672000,8.056200,149.090909,7.400375
7,36.0,34.870067,23.600000,4.500000,2.143623,36.666667,12.500000,24.166229,0.422083,22.400000,...,72.000000,98.600000,0.413100,104.296833,38.100000,106.600000,0.400000,8.021667,162.700000,7.396283
8,65.0,42.250000,45.582750,23.000000,2.815206,38.000000,8.700000,23.172333,-0.660897,17.800000,...,66.938333,94.545455,1.657950,108.256333,29.500000,109.636364,1.430750,9.478950,106.000000,7.340000
9,84.0,30.636143,39.533833,23.000000,2.183852,36.363636,9.400000,23.000000,-2.000000,15.181818,...,76.321667,96.363636,0.961300,111.000000,29.266667,67.727273,1.024000,7.156625,116.181818,7.367500
10,23.0,33.412979,32.390967,28.268333,2.238598,37.250000,11.217217,24.124167,-0.079629,22.500000,...,111.186667,100.000000,1.359433,104.244333,33.431050,111.909091,1.140000,0.070000,162.700000,7.382206
11,51.0,35.034449,31.400000,17.000000,2.392433,38.000000,10.400000,23.976667,0.844565,18.000000,...,162.000000,100.000000,0.946300,105.173833,32.700000,105.000000,2.300000,9.478050,145.000000,7.391648

In [42]:
# Number of NaN in train_features
print(imputed_train_features.shape)
print(imputed_train_features.isnull().sum())

(18995, 35)
Age                 0
EtCO2               0
PTT                 0
BUN                 0
Lactate             0
Temp                0
Hgb                 0
HCO3                0
BaseExcess          0
RRate               0
Fibrinogen          0
Phosphate           0
WBC                 0
Creatinine          0
PaCO2               0
AST                 0
FiO2                0
Platelets           0
SaO2                0
Glucose             0
ABPm                0
Magnesium           0
Potassium           0
ABPd                0
Calcium             0
Alkalinephos        0
SpO2                0
Bilirubin_direct    0
Chloride            0
Hct                 0
Heartrate           0
Bilirubin_total     0
TroponinI           0
ABPs                0
pH                  0
dtype: int64

In [43]:
# Number of NaN in the test_features
print(imputed_test_features.shape)
print(imputed_test_features.isnull().sum())

(12664, 35)
Age                 0
EtCO2               0
PTT                 0
BUN                 0
Lactate             0
Temp                0
Hgb                 0
HCO3                0
BaseExcess          0
RRate               0
Fibrinogen          0
Phosphate           0
WBC                 0
Creatinine          0
PaCO2               0
AST                 0
FiO2                0
Platelets           0
SaO2                0
Glucose             0
ABPm                0
Magnesium           0
Potassium           0
ABPd                0
Calcium             0
Alkalinephos        0
SpO2                0
Bilirubin_direct    0
Chloride            0
Hct                 0
Heartrate           0
Bilirubin_total     0
TroponinI           0
ABPs                0
pH                  0
dtype: int64

In [44]:
# Check the labels
print(labels.shape)
labels.head(12)

(18995, 16)

,pid,LABEL_BaseExcess,LABEL_Fibrinogen,LABEL_AST,LABEL_Alkalinephos,LABEL_Bilirubin_total,LABEL_Lactate,LABEL_TroponinI,LABEL_SaO2,LABEL_Bilirubin_direct,LABEL_EtCO2,LABEL_Sepsis,LABEL_RRate,LABEL_ABPm,LABEL_SpO2,LABEL_Heartrate
0,1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,12.1,85.4,100.0,59.9
1,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.8,100.6,95.5,85.5
2,100,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,16.5,88.3,96.5,108.1
3,1000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,19.4,77.2,98.3,80.9
4,10000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.6,76.8,97.7,95.3
5,10002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.5,67.4,99.1,64.6
6,10006,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.2,84.9,96.8,90.5
7,10007,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,23.8,97.0,94.3,76.0
8,10009,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,18.9,72.0,95.3,91.5
9,1001,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,14.9,83.3,99.9,117.3
10,10010,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,20.5,72.2,97.7,84.3
11,10012,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,19.8,95.8,97.6,101.6

In [45]:
# # Delect the columns with too many NaN
# for index, row in average_features.iteritems():
#     if average_features[index].isnull().sum() >= 0.7 * len(average_features[index]):
#         average_features = average_features.drop(columns=index)
#         average_test_features = average_test_features.drop(columns=index)

In [46]:
X_train = imputed_train_features
X_test = imputed_test_features

In [47]:
medical_tests = ['LABEL_BaseExcess', 'LABEL_Fibrinogen', 'LABEL_AST', 'LABEL_Alkalinephos', 'LABEL_Bilirubin_total', 'LABEL_Lactate', 'LABEL_TroponinI', 'LABEL_SaO2', 'LABEL_Bilirubin_direct', 'LABEL_EtCO2']
disease = ['LABEL_Sepsis']
vital_signs = ['LABEL_RRate', 'LABEL_ABPm', 'LABEL_SpO2', 'LABEL_Heartrate']

In [115]:
y = labels['LABEL_Heartrate']
print(y.head(12))

0      59.9
1      85.5
2     108.1
3      80.9
4      95.3
5      64.6
6      90.5
7      76.0
8      91.5
9     117.3
10     84.3
11    101.6
Name: LABEL_Heartrate, dtype: float64

In [49]:
# Standardize the training data
from sklearn.preprocessing import StandardScaler

In [50]:
# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [51]:
# Import validation methods
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV

In [52]:
# Histogram-Based Gradient Boosting Classifier and Regressor
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.ensemble import HistGradientBoostingRegressor

In [53]:
hgbC = HistGradientBoostingClassifier()

In [102]:
score = cross_validate(hgbC, X_train, y, cv=5, scoring=('roc_auc', 'accuracy'), return_train_score=True)
avgScore = {}
for k,v in score.items():
    # v is the list of scores for fold k
    avgScore[k] = sum(v)/ float(len(v))
print(avgScore)

{'fit_time': 0.2749516010284424, 'score_time': 0.005166006088256836, 'test_roc_auc': 0.6892239124921604, 'train_roc_auc': 0.9125579113227648, 'test_accuracy': 0.9423532508554884, 'train_accuracy': 0.9469465648854962}

In [ ]:
# Grid Search Cross Validation
parameters = {
 'max_iter': [1000,1200,1500],
 'learning_rate': [0.1],
 'max_depth': [25, 50, 75],
 'l2_regularization': [1.5],
 'random_state': [2022],
 }
tuning = GridSearchCV(estimator =HistGradientBoostingClassifier(), 
            param_grid = parameters, scoring='roc_auc',n_jobs=4, cv=5)
tuning.fit(X_train,y)
tuning.cv_results_, tuning.best_params_, tuning.best_score_

In [118]:
output_dict = {}
for index, row in labels.iteritems():
    if index in medical_tests:
        hgbC = HistGradientBoostingClassifier()
        y = labels[index]
        fit = hgbC.fit(X_train, y)
        proba = fit.predict_proba(X_test)[:,1]
        output_dict[index] = proba
    elif index in disease:
        hgbC = HistGradientBoostingClassifier()
        y = labels[index]
        fit = hgbC.fit(X_train, y)
        proba = fit.predict_proba(X_test)[:,1]
        output_dict[index] = proba
    elif index in vital_signs:
        hgbR = HistGradientBoostingRegressor()
        y = labels[index]
        fit = hgbR.fit(X_train, y)
        values = fit.predict(X_test)
        output_dict[index] = values
    print(output_dict)
output = pd.DataFrame(output_dict)

{}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802]), 'LABEL_Bilirubin_total': array([0.8247198 , 0.43790772, 0.162326  , ..., 0.07597577, 0.81834168,
       0.1148872 ])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802]), 'LABEL_Bilirubin_total': array([0.8247198 , 0.43790772, 0.162326  , ..., 0.07597577, 0.81834168,
       0.1148872 ]), 'LABEL_Lactate': array([0.59448092, 0.06617335, 0.24450743, ..., 0.15062308, 0.85836855,
       0.38769582])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802]), 'LABEL_Bilirubin_total': array([0.8247198 , 0.43790772, 0.162326  , ..., 0.07597577, 0.81834168,
       0.1148872 ]), 'LABEL_Lactate': array([0.59448092, 0.06617335, 0.24450743, ..., 0.15062308, 0.85836855,
       0.38769582]), 'LABEL_TroponinI': array([0.01957832, 0.12000835, 0.03404328, ..., 0.01902671, 0.02140506,
       0.01374496])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802]), 'LABEL_Bilirubin_total': array([0.8247198 , 0.43790772, 0.162326  , ..., 0.07597577, 0.81834168,
       0.1148872 ]), 'LABEL_Lactate': array([0.59448092, 0.06617335, 0.24450743, ..., 0.15062308, 0.85836855,
       0.38769582]), 'LABEL_TroponinI': array([0.01957832, 0.12000835, 0.03404328, ..., 0.01902671, 0.02140506,
       0.01374496]), 'LABEL_SaO2': array([0.21538932, 0.1090509 , 0.35346958, ..., 0.6667181 , 0.83808309,
       0.28459457])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802]), 'LABEL_Bilirubin_total': array([0.8247198 , 0.43790772, 0.162326  , ..., 0.07597577, 0.81834168,
       0.1148872 ]), 'LABEL_Lactate': array([0.59448092, 0.06617335, 0.24450743, ..., 0.15062308, 0.85836855,
       0.38769582]), 'LABEL_TroponinI': array([0.01957832, 0.12000835, 0.03404328, ..., 0.01902671, 0.02140506,
       0.01374496]), 'LABEL_SaO2': array([0.21538932, 0.1090509 , 0.35346958, ..., 0.6667181 , 0.83808309,
       0.28459457]), 'LABEL_Bilirubin_direct': array([0.1180465 , 0.02943507, 0.01783439, ..., 0.01427872, 0.13491277,
       0.01822322])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802]), 'LABEL_Bilirubin_total': array([0.8247198 , 0.43790772, 0.162326  , ..., 0.07597577, 0.81834168,
       0.1148872 ]), 'LABEL_Lactate': array([0.59448092, 0.06617335, 0.24450743, ..., 0.15062308, 0.85836855,
       0.38769582]), 'LABEL_TroponinI': array([0.01957832, 0.12000835, 0.03404328, ..., 0.01902671, 0.02140506,
       0.01374496]), 'LABEL_SaO2': array([0.21538932, 0.1090509 , 0.35346958, ..., 0.6667181 , 0.83808309,
       0.28459457]), 'LABEL_Bilirubin_direct': array([0.1180465 , 0.02943507, 0.01783439, ..., 0.01427872, 0.13491277,
       0.01822322]), 'LABEL_EtCO2': array([0.00296325, 0.03843838, 0.05889557, ..., 0.0081455 , 0.007454  ,
       0.00390872])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802]), 'LABEL_Bilirubin_total': array([0.8247198 , 0.43790772, 0.162326  , ..., 0.07597577, 0.81834168,
       0.1148872 ]), 'LABEL_Lactate': array([0.59448092, 0.06617335, 0.24450743, ..., 0.15062308, 0.85836855,
       0.38769582]), 'LABEL_TroponinI': array([0.01957832, 0.12000835, 0.03404328, ..., 0.01902671, 0.02140506,
       0.01374496]), 'LABEL_SaO2': array([0.21538932, 0.1090509 , 0.35346958, ..., 0.6667181 , 0.83808309,
       0.28459457]), 'LABEL_Bilirubin_direct': array([0.1180465 , 0.02943507, 0.01783439, ..., 0.01427872, 0.13491277,
       0.01822322]), 'LABEL_EtCO2': array([0.00296325, 0.03843838, 0.05889557, ..., 0.0081455 , 0.007454  ,
       0.00390872]), 'LABEL_Sepsis': array([0.08770467, 0.03943669, 0.04629241, ..., 0.06335769, 0.1022963 ,
       0.10113611])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802]), 'LABEL_Bilirubin_total': array([0.8247198 , 0.43790772, 0.162326  , ..., 0.07597577, 0.81834168,
       0.1148872 ]), 'LABEL_Lactate': array([0.59448092, 0.06617335, 0.24450743, ..., 0.15062308, 0.85836855,
       0.38769582]), 'LABEL_TroponinI': array([0.01957832, 0.12000835, 0.03404328, ..., 0.01902671, 0.02140506,
       0.01374496]), 'LABEL_SaO2': array([0.21538932, 0.1090509 , 0.35346958, ..., 0.6667181 , 0.83808309,
       0.28459457]), 'LABEL_Bilirubin_direct': array([0.1180465 , 0.02943507, 0.01783439, ..., 0.01427872, 0.13491277,
       0.01822322]), 'LABEL_EtCO2': array([0.00296325, 0.03843838, 0.05889557, ..., 0.0081455 , 0.007454  ,
       0.00390872]), 'LABEL_Sepsis': array([0.08770467, 0.03943669, 0.04629241, ..., 0.06335769, 0.1022963 ,
       0.10113611]), 'LABEL_RRate': array([14.18798525, 17.6886314 , 19.13278439, ..., 19.30481095,
       14.80619979, 18.32614189])}

{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802]), 'LABEL_Bilirubin_total': array([0.8247198 , 0.43790772, 0.162326  , ..., 0.07597577, 0.81834168,
       0.1148872 ]), 'LABEL_Lactate': array([0.59448092, 0.06617335, 0.24450743, ..., 0.15062308, 0.85836855,
       0.38769582]), 'LABEL_TroponinI': array([0.01957832, 0.12000835, 0.03404328, ..., 0.01902671, 0.02140506,
       0.01374496]), 'LABEL_SaO2': array([0.21538932, 0.1090509 , 0.35346958, ..., 0.6667181 , 0.83808309,
       0.28459457]), 'LABEL_Bilirubin_direct': array([0.1180465 , 0.02943507, 0.01783439, ..., 0.01427872, 0.13491277,
       0.01822322]), 'LABEL_EtCO2': array([0.00296325, 0.03843838, 0.05889557, ..., 0.0081455 , 0.007454  ,
       0.00390872]), 'LABEL_Sepsis': array([0.08770467, 0.03943669, 0.04629241, ..., 0.06335769, 0.1022963 ,
       0.10113611]), 'LABEL_RRate': array([14.18798525, 17.6886314 , 19.13278439, ..., 19.30481095,
       14.80619979, 18.32614189]), 'LABEL_ABPm': array([84.21438278, 85.27133839, 77.80945333, ..., 67.73490819,
       93.80559588, 78.23003504])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802]), 'LABEL_Bilirubin_total': array([0.8247198 , 0.43790772, 0.162326  , ..., 0.07597577, 0.81834168,
       0.1148872 ]), 'LABEL_Lactate': array([0.59448092, 0.06617335, 0.24450743, ..., 0.15062308, 0.85836855,
       0.38769582]), 'LABEL_TroponinI': array([0.01957832, 0.12000835, 0.03404328, ..., 0.01902671, 0.02140506,
       0.01374496]), 'LABEL_SaO2': array([0.21538932, 0.1090509 , 0.35346958, ..., 0.6667181 , 0.83808309,
       0.28459457]), 'LABEL_Bilirubin_direct': array([0.1180465 , 0.02943507, 0.01783439, ..., 0.01427872, 0.13491277,
       0.01822322]), 'LABEL_EtCO2': array([0.00296325, 0.03843838, 0.05889557, ..., 0.0081455 , 0.007454  ,
       0.00390872]), 'LABEL_Sepsis': array([0.08770467, 0.03943669, 0.04629241, ..., 0.06335769, 0.1022963 ,
       0.10113611]), 'LABEL_RRate': array([14.18798525, 17.6886314 , 19.13278439, ..., 19.30481095,
       14.80619979, 18.32614189]), 'LABEL_ABPm': array([84.21438278, 85.27133839, 77.80945333, ..., 67.73490819,
       93.80559588, 78.23003504]), 'LABEL_SpO2': array([98.88851251, 94.8913005 , 98.03776817, ..., 96.75042583,
       98.01515425, 98.31101296])}
{'LABEL_BaseExcess': array([0.89407056, 0.09697758, 0.04045862, ..., 0.62966381, 0.96731261,
       0.8808916 ]), 'LABEL_Fibrinogen': array([0.76381377, 0.02873488, 0.02557848, ..., 0.03323835, 0.17502183,
       0.03094884]), 'LABEL_AST': array([0.83050227, 0.38021511, 0.13493942, ..., 0.07395482, 0.83582775,
       0.11585836]), 'LABEL_Alkalinephos': array([0.89239898, 0.36978073, 0.11766749, ..., 0.08416121, 0.91936446,
       0.10369802]), 'LABEL_Bilirubin_total': array([0.8247198 , 0.43790772, 0.162326  , ..., 0.07597577, 0.81834168,
       0.1148872 ]), 'LABEL_Lactate': array([0.59448092, 0.06617335, 0.24450743, ..., 0.15062308, 0.85836855,
       0.38769582]), 'LABEL_TroponinI': array([0.01957832, 0.12000835, 0.03404328, ..., 0.01902671, 0.02140506,
       0.01374496]), 'LABEL_SaO2': array([0.21538932, 0.1090509 , 0.35346958, ..., 0.6667181 , 0.83808309,
       0.28459457]), 'LABEL_Bilirubin_direct': array([0.1180465 , 0.02943507, 0.01783439, ..., 0.01427872, 0.13491277,
       0.01822322]), 'LABEL_EtCO2': array([0.00296325, 0.03843838, 0.05889557, ..., 0.0081455 , 0.007454  ,
       0.00390872]), 'LABEL_Sepsis': array([0.08770467, 0.03943669, 0.04629241, ..., 0.06335769, 0.1022963 ,
       0.10113611]), 'LABEL_RRate': array([14.18798525, 17.6886314 , 19.13278439, ..., 19.30481095,
       14.80619979, 18.32614189]), 'LABEL_ABPm': array([84.21438278, 85.27133839, 77.80945333, ..., 67.73490819,
       93.80559588, 78.23003504]), 'LABEL_SpO2': array([98.88851251, 94.8913005 , 98.03776817, ..., 96.75042583,
       98.01515425, 98.31101296]), 'LABEL_Heartrate': array([ 82.93327564, 101.59392062,  90.85190787, ...,  81.59111912,
        95.79534667,  85.80495365])}

In [120]:
output.to_csv('prediction.csv', index=False, float_format='%.3f')

In [104]:
hgbR = HistGradientBoostingRegressor()

In [117]:
regression_score = cross_validate(hgbR, X_train, y, cv=5, scoring=('r2'), return_train_score=True)
avgScore = {}
for k,v in regression_score.items():
    # v is the list of scores for fold k
    avgScore[k] = sum(v)/ float(len(v))
print(avgScore)

{'fit_time': 0.49513421058654783, 'score_time': 0.002527952194213867, 'test_score': 0.6238192208891317, 'train_score': 0.6968501374092171}

In [ ]:
# Import the Logistic Regression model
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

In [ ]:
# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [ ]:
y_train.mean()

In [ ]:
# Test for LABEL_BaseExcess
model = svm.SVC(C=0.8, kernel='rbf', gamma=0.04, class_weight='balanced', probability=True)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)
score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
auroc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print('y_pred_train mean: ', y_pred_train.mean())
print('y_test mean: ', y_test.mean())
print('y_pred_test mean: ', y_pred.mean())
print('train accuracy: ', score)
print('test accuracy: ', test_score)
print('auroc score: ', auroc_score)

In [ ]:
y = labels['LABEL_Fibrinogen']
y

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [ ]:
y_train.mean()

In [ ]:
# Test for LABEL_Fibrinogen
model = svm.SVC(C=1, kernel='rbf', gamma=0.01, class_weight='balanced', probability=True)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)
score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
auroc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print('y_pred_train mean: ', y_pred_train.mean())
print('y_test mean: ', y_test.mean())
print('y_pred_test mean: ', y_pred.mean())
print('train accuracy: ', score)
print('test accuracy: ', test_score)
print('auroc score: ', auroc_score)

In [ ]:
# Test for LABEL_AST
y = labels['LABEL_AST']
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

print(y_train.mean())

model = svm.SVC(C=1, kernel='rbf', gamma=0.02, class_weight='balanced', probability=True)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)
score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
auroc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print('y_pred_train mean: ', y_pred_train.mean())
print('y_test mean: ', y_test.mean())
print('y_pred_test mean: ', y_pred.mean())
print('train accuracy: ', score)
print('test accuracy: ', test_score)
print('auroc score: ', auroc_score)

In [ ]:
# Test for LABEL_Alkalinephos
y = labels['LABEL_Alkalinephos']
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

print(y_train.mean())

model = svm.SVC(C=1, kernel='rbf', gamma=0.01, class_weight='balanced', probability=True)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)
score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
auroc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print('y_pred_train mean: ', y_pred_train.mean())
print('y_test mean: ', y_test.mean())
print('y_pred_test mean: ', y_pred.mean())
print('train accuracy: ', score)
print('test accuracy: ', test_score)
print('auroc score: ', auroc_score)

In [ ]:
# Test for LABEL_Bilirubin_total
y = labels['LABEL_Bilirubin_total']
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

print(y_train.mean())

model = svm.SVC(C=0.8, kernel='rbf', gamma=0.075, class_weight='balanced', probability=True)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)
score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
auroc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print('y_pred_train mean: ', y_pred_train.mean())
print('y_test mean: ', y_test.mean())
print('y_pred_test mean: ', y_pred.mean())
print('train accuracy: ', score)
print('test accuracy: ', test_score)
print('auroc score: ', auroc_score)

In [ ]:
# Test for LABEL_Lactate
y = labels['LABEL_Lactate']
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

print(y_train.mean())

model = svm.SVC(C=1, kernel='rbf', gamma=0.01, class_weight='balanced', probability=True)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)
score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
auroc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print('y_pred_train mean: ', y_pred_train.mean())
print('y_test mean: ', y_test.mean())
print('y_pred_test mean: ', y_pred.mean())
print('train accuracy: ', score)
print('test accuracy: ', test_score)
print('auroc score: ', auroc_score)

In [ ]:
# Test for LABEL_TroponinI
y = labels['LABEL_TroponinI']
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

print(y_train.mean())

model = svm.SVC(C=1, kernel='rbf', gamma=0.01, class_weight='balanced', probability=True)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)
score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
auroc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print('y_pred_train mean: ', y_pred_train.mean())
print('y_test mean: ', y_test.mean())
print('y_pred_test mean: ', y_pred.mean())
print('train accuracy: ', score)
print('test accuracy: ', test_score)
print('auroc score: ', auroc_score)

In [ ]:
# Test for LABEL_SaO2
y = labels['LABEL_SaO2']
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

print(y_train.mean())

model = svm.SVC(C=1, kernel='rbf', gamma=0.01, class_weight='balanced', probability=True)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)
score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
auroc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print('y_pred_train mean: ', y_pred_train.mean())
print('y_test mean: ', y_test.mean())
print('y_pred_test mean: ', y_pred.mean())
print('train accuracy: ', score)
print('test accuracy: ', test_score)
print('auroc score: ', auroc_score)

In [ ]:
# Test for LABEL_Bilirubin_direct
y = labels['LABEL_Bilirubin_direct']
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

print(y_train.mean())

model = svm.SVC(C=1, kernel='rbf', gamma=0.01, class_weight='balanced', probability=True)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)
score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
auroc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print('y_pred_train mean: ', y_pred_train.mean())
print('y_test mean: ', y_test.mean())
print('y_pred_test mean: ', y_pred.mean())
print('train accuracy: ', score)
print('test accuracy: ', test_score)
print('auroc score: ', auroc_score)

In [ ]:
# Test for LABEL_EtCO2
y = labels['LABEL_EtCO2']
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

print(y_train.mean())

model = svm.SVC(C=1, kernel='rbf', gamma=1, class_weight='balanced', probability=True)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)
score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
auroc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print('y_pred_train mean: ', y_pred_train.mean())
print('y_test mean: ', y_test.mean())
print('y_pred_test mean: ', y_pred.mean())
print('train accuracy: ', score)
print('test accuracy: ', test_score)
print('auroc score: ', auroc_score)

In [ ]:
# Test for LABEL_Sepsis
y = labels['LABEL_Sepsis']
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Standardize the training features and test features
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

print(y_train.mean())

model = svm.SVC(C=1, kernel='rbf', gamma=1, class_weight='balanced', probability=True)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train)
y_pred = model.predict(X_test)
score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
auroc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print('y_pred_train mean: ', y_pred_train.mean())
print('y_test mean: ', y_test.mean())
print('y_pred_test mean: ', y_pred.mean())
print('train accuracy: ', score)
print('test accuracy: ', test_score)
print('auroc score: ', auroc_score)

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV

In [ ]:
print(X)

In [ ]:
ss = StandardScaler()
X = ss.fit_transform(X)
X

In [ ]:
model = svm.SVC(C=0.1, kernel='rbf', gamma=0.01, class_weight='balanced')
scores = cross_validate(model, X_train, y_train, cv=5, scoring=('roc_auc', 'accuracy'))
scores

In [ ]:
model = svm.SVC(C=0.2, kernel='rbf', gamma=0.02, class_weight='balanced')
scores = cross_validate(model, X, y, cv=5, scoring=('roc_auc', 'accuracy'))
scores

In [ ]:
# Use Cross validation to find the best C and gamma
def optimize_C_gamma(X, y, index):
    print('Scores for label: ', index, 'Start! \n')
    scores = []
    for c in np.arange(0.1, 1.1, 0.3):
        for g in np.arange(0.01, 0.25, 0.04):
            print('Current C: ', c)
            print('Current Gamma: ', g)
            # Train the SVM model
            model = svm.SVC(C=c, kernel='rbf', gamma=g, class_weight='balanced')
            score = cross_validate(model, X, y, cv=5, scoring=('roc_auc', 'accuracy'), return_train_score=True)
            avgScore = {}
            avgScore['LABEL'] = index
            for k,v in score.items():
                # v is the list of grades for student k
                avgScore[k] = sum(v)/ float(len(v))
            avgScore.pop('fit_time')
            avgScore.pop('score_time')
        
            scores.append(avgScore)
            print(avgScore, '\n')
            print('Interate once!\n')
    print('Scores for label: ', index, 'Finished! \n')
    return scores

In [ ]:
def gridsearch_C_gamma(X, y, index):
    print('Scores for label: ', index, 'Start! \n')
    params_grid = {'C': np.arange(0.1, 1, 0.3), 'gamma': np.arange(0.01, 0.2, 0.03)}
    model = svm.SVC()
    grid_search = GridSearchCV(model, param_grid = params_grid, scoring='roc_auc')
    grid_search.fit(X, y)
    score = grid_search.score(X, y)
    return score

In [ ]:
# Use KNN to classify
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
X = X
y = labels['LABEL_BaseExcess']

def search_knn(X, y, index):
    print('Scores for label: ', index, 'Start! \n')
    scores = []
    for k in range(1,20,2):
        print('K: ', k)
        knn = KNeighborsClassifier(n_neighbors=k)
        score = cross_validate(knn, X, y, cv=5, scoring=['roc_auc', 'accuracy'], return_train_score=True)
        avgScore = {}
        avgScore['LABEL'] = index
        for k,v in score.items():
            # v is the list of grades for student k
            avgScore[k] = sum(v)/ float(len(v))
        avgScore.pop('fit_time')
        avgScore.pop('score_time')
        scores.append(avgScore)
        print(avgScore, '\n')
        print('Interate once!\n')
    print('Scores for label: ', index, 'Finished! \n')
    print(scores)

In [ ]:
def search_knn(X, y, index):
    print('Scores for label: ', index, 'Start! \n')
    scores = []
    for k in range(201,400,4):
        print('K: ', k)
        knn = KNeighborsClassifier(n_neighbors=k)
        score = cross_validate(knn, X, y, cv=5, scoring=['roc_auc', 'accuracy'], return_train_score=True)
        avgScore = {}
        avgScore['LABEL'] = index
        for k,v in score.items():
            # v is the list of grades for student k
            avgScore[k] = sum(v)/ float(len(v))
        avgScore.pop('fit_time')
        avgScore.pop('score_time')
        scores.append(avgScore)
        print(avgScore, '\n')
        print('Interate once!\n')
    print('Scores for label: ', index, 'Finished! \n')

In [ ]:
X = X
y = labels['LABEL_Sepsis']
y.mean()

In [ ]:
knn = KNeighborsClassifier(n_neighbors=10000)
score_test = cross_validate(knn, X, y, cv=5, scoring=['roc_auc', 'accuracy'], return_train_score=True)
avgScore_test={}
avgScore_test['LABEL'] = 'LABEL_Sepsis'
for k,v in score_test.items():
    # v is the list of output for item k
    avgScore_test[k] = sum(v)/ float(len(v))
# avgScore_test.pop('fit_time')
# avgScore_test.pop('score_time')
print(avgScore_test, '\n')

In [ ]:
search_knn(X, labels['LABEL_Sepsis'], 'LABEL_Sepsis')

In [ ]:
# Train models for each medical test
medical_tests = ['LABEL_BaseExcess', 'LABEL_Fibrinogen', 'LABEL_AST', 'LABEL_Alkalinephos', 'LABEL_Bilirubin_total', 'LABEL_Lactate', 'LABEL_TroponinI', 'LABEL_SaO2', 'LABEL_Bilirubin_direct', 'LABEL_EtCO2']

for index, row in labels.iteritems():
    if index in medical_tests:
        scores_for_label = search_knn(X, labels[index], index)

In [ ]:
scores = optimize_C_gamma(X, y, 'LABEL_BaseExcess')

In [ ]:
model = svm.SVC(C=0.8, kernel='rbf', gamma=0.04, class_weight='balanced')
scores = cross_validate(model, X, y, cv=5, scoring=('roc_auc', 'accuracy'), return_train_score=True)
scores

In [ ]:
# Train models for each medical test
medical_tests = ['LABEL_BaseExcess', 'LABEL_Fibrinogen', 'LABEL_AST', 'LABEL_Alkalinephos', 'LABEL_Bilirubin_total', 'LABEL_Lactate', 'LABEL_TroponinI', 'LABEL_SaO2', 'LABEL_Bilirubin_direct', 'LABEL_EtCO2']

# Iterate the medical tests
for index, row in labels.iteritems():
    if index in medical_tests:
        scores_for_label = optimize_C_gamma(X, labels[index], index)

In [ ]:
# SGD Classifier
from sklearn.linear_model import SGDClassifier

In [ ]:
X = X
y = labels['LABEL_Sepsis']

In [ ]:
sgd = SGDClassifier(loss='modified_huber', max_iter=1000, tol=1e-3, class_weight='balanced')

In [ ]:
scores = cross_validate(sgd, X, y, cv=5, scoring=('roc_auc', 'accuracy'), return_train_score=True)
print(scores)